spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

flyway:
  url: jdbc:h2:mem:db;INIT=CREATE SCHEMA IF NOT EXISTS validator_schema
  user: sa
  password: sa
  schemas: validator_schema